<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca_revistas [
<!ELEMENT biblioteca_revistas (revista+)>

<!ELEMENT revista (titulo, numero, indice, secciones)>
<!ATTLIST revista id ID #REQUIRED>
<!ATTLIST revista tipo_clase (informatica | corazon | coches | investigacion | otras) #IMPLIED>
<!ATTLIST revista num_paginas CDATA #REQUIRED>

<!ELEMENT titulo (#PCDATA)>

<!ELEMENT numero (#PCDATA)>

<!ELEMENT indice (num_seccion+)>
<!ELEMENT num_seccion (#PCDATA)>

<!ELEMENT secciones (seccion+)>

<!ELEMENT seccion (titulo_seccion, contenido)>
<!ATTLIST seccion num_paginas CDATA #REQUIRED>

<!ELEMENT titulo_seccion (#PCDATA)>

<!ELEMENT contenido (#PCDATA)>
<!ATTLIST contenido enlace CDATA #REQUIRED>
]>

<biblioteca_revistas>
    <revista id="R001" tipo_clase="informatica" num_paginas="150"> 
        <titulo>Computer Hoy</titulo>
        <numero>27</numero>
        <indice>
            <num_seccion>Tecnologia</num_seccion>
            <num_seccion>Entretenimiento</num_seccion>
            <num_seccion>Gaming</num_seccion>
        </indice>
        <secciones>
            <seccion num_paginas="50">
                <titulo_seccion>Tecnologia</titulo_seccion>
                <contenido enlace="https://computerhoy.com/tecnologia"> 
                    Contenido
                </contenido>
            </seccion>
            <seccion num_paginas="50">
                <titulo_seccion>Entretenimiento</titulo_seccion>
                <contenido enlace="https://computerhoy.com/entretenimiento">
                    Contenido
                </contenido>
            </seccion>
            <seccion num_paginas="50">
                <titulo_seccion>Gaming</titulo_seccion>
                <contenido enlace="https://computerhoy.com/gaming">
                    Contenido
                </contenido>
            </seccion>
        </secciones>
    </revista>
    <revista id="R002" tipo_clase="corazon" num_paginas="120">
        <titulo>Lectura</titulo>
        <numero>1566</numero>
        <indice>
            <num_seccion>Actualidad</num_seccion>
            <num_seccion>Casas Reales</num_seccion>
        </indice>
        <secciones>
            <seccion num_paginas="60">
                <titulo_seccion>Actualidad</titulo_seccion>
                <contenido enlace="https://www.lecturas.com/actualidad">
                    Contenido
                </contenido>
            </seccion>
            <seccion num_paginas="60">
                <titulo_seccion>Casas Reales</titulo_seccion>
                <contenido enlace="https://www.lecturas.com/actualidad/casas-reales">
                    Contenido
                </contenido>
            </seccion>
        </secciones>
    </revista>
    <revista id="R003" tipo_clase="coches" num_paginas="100">
        <titulo>Autofacil</titulo>
        <numero>17</numero>
        <indice>
            <num_seccion>Reportajes</num_seccion>
            <num_seccion>Novedades</num_seccion>
        </indice>
        <secciones>
            <seccion num_paginas="50">
                <titulo_seccion>Reportajes</titulo_seccion>
                <contenido enlace="https://www.autofacil.es/reportajes/">
                    Contenido
                </contenido>
            </seccion>
            <seccion num_paginas="50">
                <titulo_seccion>Novedades</titulo_seccion>
                <contenido enlace="https://www.autofacil.es/novedades/">
                    Contenido
                </contenido>
            </seccion>
        </secciones>
    </revista>
</biblioteca_revistas>